import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/FrontEndLogic/ReduxToolkit/Provider";
import AuthContext from "@/FrontEndLogic/Context/AuthContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import RefreshProvider from "@/FrontEndLogic/ReduxToolkit/RefreshProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Job Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthContext>
          <Toaster
        position="top-center"
        reverseOrder={false}
        gutter={8}
        containerClassName=""
        containerStyle={{}}
        toastOptions={{
          // Define default options
          className: '',
          duration: 5000,
          style: {
            background: '#363636',
            color: '#fff',
          },

          // Default options for specific types
          success: {
            duration: 3000,
            theme: {
              primary: 'green',
              secondary: 'black',
            },
          },
        }}
      />
            <Navbar/>
            {children}
            <Footer/>
          </AuthContext>
        </Providers>
        </body>
    </html>
  );
}
